"""empty message

Revision ID: 46837266c695
Revises: a3a1362c4e4d
Create Date: 2024-05-19 17:07:02.171235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46837266c695'
down_revision = 'a3a1362c4e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('schools',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('schools',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
