"""empty message

Revision ID: 507fb05793ab
Revises: 
Create Date: 2024-05-19 13:30:25.025908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507fb05793ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_adminuser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('passwd', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_adminuser', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_adminuser_name'), ['name'], unique=True)

    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    with op.batch_alter_table('tb_adminuser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_adminuser_name'))

    op.drop_table('tb_adminuser')
    # ### end Alembic commands ###
