"""empty message

Revision ID: a3a1362c4e4d
Revises: b9011d84ac1d
Create Date: 2024-05-19 17:03:33.213670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a1362c4e4d'
down_revision = 'b9011d84ac1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nicheng', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('schools', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('brief', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('brief')
        batch_op.drop_column('sex')
        batch_op.drop_column('schools')
        batch_op.drop_column('nicheng')

    # ### end Alembic commands ###
