"""empty message

Revision ID: b3c9820ec342
Revises: b66020bbe9fd
Create Date: 2024-05-25 22:03:55.115712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c9820ec342'
down_revision = 'b66020bbe9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('anxiety', sa.Integer(), nullable=True),
    sa.Column('depress', sa.Integer(), nullable=True),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_score')
    # ### end Alembic commands ###
